# Generated by Django 4.2.16 on 2026-06-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True, verbose_name='评分')),
                ('value', models.IntegerField(null=True, verbose_name='数量')),
            ],
            options={
                'db_table': 'part1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='景点名称')),
                ('value', models.IntegerField(null=True, verbose_name='评论数量')),
            ],
            options={
                'db_table': 'part2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='价格区间')),
                ('value', models.IntegerField(null=True, verbose_name='景点数量')),
            ],
            options={
                'db_table': 'part3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='区域名称')),
                ('value', models.IntegerField(null=True, verbose_name='景点数量')),
            ],
            options={
                'db_table': 'part4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='词语')),
                ('value', models.IntegerField(null=True, verbose_name='出现次数')),
            ],
            options={
                'db_table': 'part5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='省份')),
                ('value', models.IntegerField(null=True, verbose_name='景点数量')),
            ],
            options={
                'db_table': 'part6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='城市名称')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='景点名称')),
                ('value', models.FloatField(null=True, verbose_name='热度评分')),
            ],
            options={
                'db_table': 'part7',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Part8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='省份')),
                ('travel_num', models.IntegerField(null=True, verbose_name='景点数量')),
                ('avg_score', models.FloatField(null=True, verbose_name='平均评分')),
            ],
            options={
                'db_table': 'part8',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='travelinfo',
            table='home_travelinfo',
        ),
        migrations.CreateModel(
            name='CleanedAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='景点名称')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='城市')),
                ('area', models.CharField(blank=True, max_length=255, null=True, verbose_name='区域')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('hotness', models.FloatField(default=0.0, verbose_name='热度')),
                ('review_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('cost', models.FloatField(default=0.0, verbose_name='门票价格(元)')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
                ('center_distance_km', models.FloatField(default=0.0, verbose_name='距市中心(km)')),
                ('is_coord_valid', models.BooleanField(default=False, verbose_name='坐标是否有效')),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned', to='home.travelinfo', verbose_name='原始数据')),
            ],
            options={
                'verbose_name_plural': '清洗后景点数据',
                'db_table': 'home_cleaned_attraction',
                'indexes': [models.Index(fields=['city', 'is_coord_valid'], name='home_cleane_city_39fe2f_idx'), models.Index(fields=['name'], name='home_cleane_name_c82907_idx')],
            },
        ),
    ]
