# Generated by Django 4.2.16 on 2026-01-22 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('uemail', models.CharField(max_length=40, verbose_name='邮箱')),
                ('address', models.CharField(default='', max_length=30, verbose_name='地址')),
                ('uyoubian', models.CharField(default='', max_length=30, verbose_name='邮编')),
                ('uphone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('avatar', models.CharField(default='', max_length=255, verbose_name='头像')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
