# Generated by Django 4.2.16 on 2026-06-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_address_userinfo_uaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uphone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uyoubian',
        ),
    ]
